### ISSUE TITLE
Later hand on 43v ?

### ISSUE THREAD

**Issue by brclar15** [hmteditors/hmt-3#1]
Need to check with others to see if the interlinears on 43v are a later hand. If so, how then should we deal with them?

urn:cite:hmt:vaimg.VA043VN-0545@0.434,0.2246,0.466,0.1533

**Comment by StephanieML** [comment]
nah, those are definitely the original hand. the ink color looks slightly different, but that's probably just normal fading and the scribe starting with fresh ink. SO treat them as normal interlinears.

**Comment by brclar15** [comment]
right on, I'll take care of it
